### ISSUE TITLE
Entry Point

### ISSUE THREAD

**Issue by drparadoxical** [drparadoxical/aeon-project-planning#3]
Team, 

I'm continuing what was started [over in aeon-rebase](https://github.com/drparadoxical/aeon-rebase/issues/6) so we've got a proper entry point for the time being, and so decisions can be discussed and made. I'll restate the main talking points from that issue again here, in the list below. 

Again, welcome, and for those who introduced themselves, thanks again. For those who wish to do so, please and by all means. 

Let's open the following up for discussion, and if and when need be allow for any given point to create it's own room in one of the gitter channels accordingly, which is as good a place to start as any, conveniently enough. 

1. Gitter Channels
   * [aeon-project-planning](https://gitter.im/aeon-project-planning/Lobby), Gitter badge also on project's README.md
   * [aeon-rebase](https://gitter.im/aeon-rebase/Lobby), badge also available on README.md
2. For the next few days, I'd like to contain planning and discussion here in aeon-project-planning and the aeon-project-planning Gitter, if you don't mind, so we can discuss and decide and have common ground up to the point just after SPMP and SRS internal and external review, after the holidays. By now it's probably starting to feel a bit like unnecessary corporate process and paperwork that's just slowing us down, but the intent is to simply get through a bare minimum of planning, ensure the community is informed and the plan and requirements will get us to the expected result of our rebase efforts, make sure we've everything we need, all resources identified and nailed down and brought into the fold, and so on. 
   * I'm currently drafting that SPMP and SRS, you'll see it added here as soon as first draft is completed, and directly or indirectly, however he responds, Smooth will provide feedback and insight on the plan and specification accordingly. This won't be too deep or unnecessarily exhaustive, because we all know this boils down to "well, just rebase, and we're done", but again, I'm not intending for this to slow or weigh us down, I'm intending to establish rigid structure, comms, ensure all involved understand the resources and pipelines, double verify our intent with community and core developer, and move right on into things. 
3. As I mentioned on the other issue linked to above, the following are available to the team, and I need for you all to add to and strike from the list:
   1. Firebase account space (including team members based on whatever address they're comfortable with using)
   2. Google Cloud Platform account space  (including team members based on whatever address they're comfortable with using)
   3. Github Constant Integration (and whatever else from the marketplace you all think we need)
   4. Trello, I believe was mentioned and requested, but those to whom I speak, please clarify and provide specifics
   * Beating a dead horse, but reiterating to be sure it's well understand, no one need buy anything with their own money, I've created an operating budget for our work together, and it certainly doesn't require breaching anonymity, or even that I be involved or have access to whatever it is that's needed. In short, you're all bankrolled, and I've no interest in doing so other than ensuring no one's going to hit themselves with a $500 hosting fee after forgetting to turn off their VMs set up for nodes for dev and production testing, or whatever
4. We're currently leaning towards aeon-rebase/ being instantiated as project space by cloning the Monero v0.11.1.0 tag, [further details on that discussion here](https://github.com/drparadoxical/aeon-rebase/issues/5), raise objections or contribute to the discussion accordingly, and we'll make a decision here. 
5. We'll need to determine our own level of security and visibility for our Github repos and our Gitter channels. Currently, everything's wide open, and we should discuss and decide upon whether to box in the aeon-rebase work to collaborators until we're done, make Gitter private view and collaborator access only, or simply leave everything wide open. 
   1. In the interest of transparency, leaving everything wide open makes the most sense, and I'm raising this point to determine if we need to raise any walls to minimize or reject unwanted influence, distraction, threat, whatever. 
6. Team members
   1. /u/D13Devops, @devopsralf - lending their Web/UI Integration Development hand
   2. /u/DrParadoxically, @drparadoxical - lending his Anything&Everything hand
   3. /u/exeunt_bits, @qskousen - lending their Web/Systems Development hand
   4. /u/guzzi_jones, @guzzijones - lending their Full Stack Development hand 
   5. @routed27  - lending their QA/PM hand 
   6. @thejourneydude  - lending their Web/Systems Development hand
7. Membership protocol
   1. You come and go as you please
   2. You work as you please
   3. You assume whatever work you please
   4. Any direction or management or guidelines established now or in the future are suggestions, all is open to discussion, up for debate
   5. I am not a tie breaker or executive decision maker, and in these repos for this work, consensus is king
8. Offensive Strategem
   1. aeon-rebase hit hard primarily by guzzi, routed27, and myself
   2. aeon-webwallet hit hard by devops, gsk, journey, routed27, and myself
9. Bounties
   1. I've made it clear that I refuse to accept the bounties on anyone's behalf, and while anyone can come and go as they please, will restrict our efforts for a time so that this team and its efforts are contained, and in the event the deliverable receives a bounty's reward, then receives, directly and absolutely not with me as a proxy cash distributor, their share of the bounty accordingly 
      * This is absolutely open for discussion and debate, because we'll waste no time whatsoever on greed, and will not assume and wait for anyone's expectations to be dashed against any rocky shores. 

Long story short, welcome again, be aware of points 1 and 2, please open point 3 up for discussion and lets compile that list, 4 is still open for debate, though again we're leaning towards cloning the 0.11.1.0 tag as our starting point, and 5 is now up for discussion and debate so we can make decisions and change settings and configurations accordingly if need be. 

**Edit/Addition:** Added points 6, 7, 8, and 9, with 9 being something that needs to very much be out in the open now, and cannot wait till after anyone's dedicated anything significant on any front. 

**Edit/Addition:** @routed27 just showed up to the party, final member here, all accounted for. 

**Edit/Addition:** @mining_for_aeon decided he'd rather approach this problem set differently, and informed us that he won't be joining us here for and during this work. 

**Edit/Addition:** Those who wants out or have dropped off the radar or simply not shown up, looks like the team's formed now, and those defined above are collaborators on all three repositories.

**Comment by thejourneydude** [comment]
Some feedback with points 3 and 5

3. This looks fine to me. I imagine down the road as we get our hands dirty we will realize some products work for us, some don't and adjust accordingly.

5. I'm fine with keeping everything visible for now. That said, if others feel we should keep things closed off and have good reason to do so, I'm willing to consider that too. I imagine like in point 3, this may change according to circumstances and necessity.

@drparadoxical Thanks for putting together an operating budget and all your work so far!

**Comment by drparadoxical** [comment]
@thejourneydude, not a problem, just so long as it's well understood I'm not trying to buy or own anything, no interest in even looking in that direction, just want to make sure we're well armed and no one's left suffering silently.

**Comment by drparadoxical** [comment]
Two edits and additions made recently, if you haven't seen this since it was initially created, FYI. 

All, please let me know if how I've described you is either incorrect, a bit off, or not what you had in mind. Take it offline if need be, and just PM me, however the hell that works when everything's public. 

It is not a restriction, nor a strict delegation, you are what you want to be, and do work you want to do. The strategy as defined is my current understanding of how to quickly, completely, correctly, and simply get us to the other side of the work, and everyone handsomely paid directly and accordingly. 

Black flag raised high on this ship, as a fact.

**Comment by drparadoxical** [comment]
Now, Happy Holidays. Rest up, all of you, I'll be back here shortly as well with SPMP and SRS in hand and public review underway. 

Take the next few days to not forget about Christmas and family and such. 

I'm giving us all until Dec. 29th, 2017, space and room to breath, time to talk and plan things out, time for people to decide if they're here or if they'd rather not be, before we disembark. 

I hope those who have stepped up, all of you, are all here a week from now, still. Not a single hard damn feeling if you decide otherwise, but again I sure do hope you stick around. 

For those who were on the web wallet hunt, I'll shore up the current work and push it into the web wallet repo as well, which we'll need in order to fully understand that work and its starting point, given what's already been accomplished. 

Feel free to keep on doing what you're doing, this period is meant for settling, discussing, deciding, not a demand for stagnation and silence. We're human, and we all need time to think, but we're also busy people, and I wanted to avoid shoving off and unintentionally leaving anyone behind for no other reason than missing the boat by a matter of hours due to work, life, family, kid, and so on.

**Comment by drparadoxical** [comment]
Those who wants out or have dropped off the radar or simply not shown up, looks like the team's formed now, and those defined above are collaborators on all three repositories. 

Diving in deep today gentlemen, you'll see some movement from my end, Merry Christmas Eve to all.

Leaving this settling period open till the 29th as planned, but we'll go ahead and get to it, and if someone else comes along wanting to join us, then great, we'll deal with things as they occur past this point.

**Comment by routed27** [comment]
Merry Christmas

**Comment by fabloisgone** [comment]
Hey guys sorry I am late posting. Been busy coding/visiting with family. I have already spent a decent amount of time diving into the code. Excited to be a part of this. Can we set up a good place to chat about this and get a final count for the team? 

Lets do this

- fabloisgone

**Comment by drparadoxical** [comment]
In the main post up top you'll find links to the Gitter channels - not a lot of movement there just yet, most of it has been contained here in discussions per issue, but those Gitter channels and these issues are wide open. 

I'd suggest reading up, catching yourself up to speed, and the others threw out specializations when they introduced themselves, so while you certainly don't have to do so yourself, it may help us all out to know your strengths and what you've generally been able to accomplish thus far. 

One way or another, putting this puzzle entirely together is our objective here, truth be told. Every little bit counts.

**Comment by guzzijones** [comment]
I am in agreement with everything here.

**Comment by drparadoxical** [comment]
Closing this, and conversation and talking points are carried over into SPMP and team Gitter channel conversations.
