### ISSUE TITLE
Schedule for Internal Huddles

### ISSUE THREAD

**Issue by drparadoxical** [drparadoxical/aeon-project-planning#5]
Gather feedback from all team members on the days and times in which they are willing to commit to huddling up with the rest of the team on internal comms.

**Comment by drparadoxical** [comment]
9:00pm-3:00am 7 days a week for me, let's see if we can find those pockets where the team's all there, then pick a few and reserve them specifically for team discussion, review, planning, current goings on, next steps, etc.

**Comment by routed27** [comment]
Please include timezone when making an entry.

**Comment by drparadoxical** [comment]
Thanks @routed27, had it in mind, but the fingers didn't follow orders. 

9:00pm-3:00am EST.

**Comment by routed27** [comment]
Fully understand as I do it all the time. I'm good from post 9:00pm EST most days with a moving end time.

**Comment by qskousen** [comment]
I can come in late 10-1030 EST depending on how quick we get the kids to
bed.

**Comment by routed3** [comment]
Common meeting times for rebase efforts established and distributed to team members. Issue can be closed
