### ISSUE TITLE
Gather SSH Keys from Collaborators

### ISSUE THREAD

**Issue by drparadoxical** [drparadoxical/aeon-project-planning#7]
Gather public SSH keys from each collaborator so they may be added to the authorized_keys files on, and thus be allowed access to, all remote hosts used for testing and development.

**Comment by qskousen** [comment]
ssh-rsa
AAAAB3NzaC1yc2EAAAABJQAAAIEAo/noCzTQbH2/wt27QcdyAqQBAQlL5m7qVOgdhuZQCXTZv3FSZRDa4JX+nP4haw16jq2CCIzGwsYmfwRj3k5oeiKmSTtCJQm7U3Fvp4o2sutbt7oQ5xKLSul3XqkMJPz+d4YVELClLArq5oKzXWKNgvqbOUD2kdLFVdLi4Opd8WM=
rsa-key-20140623

**Comment by drparadoxical** [comment]
Keys gathered, systems instantiated with authorized keys in place, closing now.
